### ISSUE TITLE
Autosample titrator

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/alk_dic#27]
- [ ] Research autosample titrator systems (email Irene and Simone)

**Comment by pmcelhany** [comment]
@michaelmaher114 @KROVINSKI @dmperez89 
Would it be possible for one person to keep two alkalinity titrators going at once? E.g. Switch back and forth between starting one titrator while the other one is doing the titration.

**Comment by KROVINSKI** [comment]
@michaelmaher114 mike, the software can do two at a time or do I remember wrong from uw?

**Comment by michaelmaher114** [comment]
Well you don't really need two titrators, but two reaction vessels, both
hooked up to the water bath.  The method is to prepare one sample while the
other is running, then change them out, and clean / prepare the next, etc.

It is possible to run a few more samples per day this way.  However, I was
surprised when Danielle said they were doing 30 samples a day?  This is
more than I already thought was possible.

**Comment by pmcelhany** [comment]
If needed, we could get two computers. Is it physically possible for one person to  run 2 at a time to increase number of samples in a day?

**Comment by pmcelhany** [comment]
Another reaction vessel sounds relatively inexpensive. Can someone get the specs on ordering another one? 

I've been thinking about how to get our own titrator. If we got one asap and still have alex's on loan, we would have two of them for awhile until alex asks for his back. Would that speed things up?

**Comment by dmperez89** [comment]
@pmcelhany @michaelmaher114 @KROVINSKI 30 samples a day is still pretty ambitious, and that's assuming you can get started early and run continuously without problems (running out of acid or gas, no weird readings, etc). The other day I was only running two samples per treatment since we were running out of acid so if we want more samples per treatment in addition to almost double the treatments, it's almsot definitely a two day process. 
I'm hoping we can get started bubbling early tomorrow so that way we can run some of the titrations in the afternoon. I think that's our only hope of running everything before the weekend.

**Comment by pmcelhany** [comment]
Best option is to get a second Dickson titrator...
