### ISSUE TITLE
Missing Samples - 

### ISSUE THREAD

**Issue by KROVINSKI** [NWFSC-OA-lab/alk_dic#6]
@michaelmaher114 
@dmperez89 
@pmcelhany 

Paul,

There is a mismatch between samples sent and samples received. I've commented out which experiments I thought matched each experiment. I added a new column to create a deep notes section explaining if 9 bottles were sent but only two were processed. 

https://drive.google.com/file/d/1EG8FvA818re37KDPVDmlAKehsXhB0X4Y/view?usp=sharing
under name 
"milford_run_samples_insitu_data(deepnotes).csv"

(1) We weren't sure where this file was generated
1-a Was this a file created by the milford lab or did you sparse something down

(2) I can go in with salinity files from Mike- what to do about treatments?
2-a how should we handle day and night set points?

V/r,
Kate

**Comment by KROVINSKI** [comment]
Paul I could not assign to yourself.

**Comment by KROVINSKI** [comment]
maybe I can assign after all...

**Comment by pmcelhany** [comment]
If a repository is private, only one person can be assigned. to
assign multiple people, the repository has to be changed to public (go to
the repository settings "danger zone"). Since there is nothing secret in
the repo, it is OK to change the repo to public. If we spend some money, we
can upgrade our github to allow multiple assignees on private repos, but it
doesn't seem worth it unless the data are sensitive.

**Comment by pmcelhany** [comment]
Review if we need these data
